export const Products=[{
    name:"Brushed Raglan Sweatshirt",
    src: { src: "/product.png"},
    category:"Women",
    price:"$195",
    product:"Sweater",
    id:"1",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."] 
},{
    name:"Cameryn Sash Tie Dress",
    src: { src: "/product2.png" },
    category:"Women",
    price:"$545",
    product:"Dress",
    id:"2",
    productDetail:"Elevate your style with the Cameryn Sash Tie Dress. This elegant piece boasts a waist-accentuating sash tie, intricate lace detailing, and a breathable blend for comfort. Versatile and timeless, it's perfect for any occasion, seamlessly combining sophistication and style.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Flex Sweatshirt",
    src: { src: "/product3.png" },
    category:"Women",
    price:"$175",
    product:"Sweater",
    id:"3",
    productDetail:"Indulge in the comfort of our Flex Sweatshirt. This cozy sweater is designed for versatility and style. Its soft fabric and relaxed fit make it perfect for casual days or lounging at home. The timeless design ensures you stay fashionable and comfortable.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Flex Sweatpants",
    src: { src: "/product4.png" },
    category:"Women",
    price:"$175",
    product:"Pants",
    id:"4",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Pink Fleece Sweatpants",
    src: { src: "/product5.png" },
    category:"Women",
    price:"$195",
    product:"Pants",
    id:"5",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Lite Sweatpants",
    src: { src: "/product6.png" },
    category:"Women",
    price:"$150",
    product:"Pants",
    id:"6",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Imperial Alpaca Hoodie",
    src: { src: "/product7.png" },
    category:"Women",
    price:"$545",
    product:"Jackets",
    id:"7",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Muscle Tank",
    src: { src: "/product8.png" },
    category:"Women",
    price:"$75",
    product:"T-shirts",
    id:"8",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Brushed Bomber",
    src: { src: "/product9.png" },
    category:"Women",
    price:"$225",
    product:"Jacket",
    id:"9",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Flex Push Button Bomber",
    src: { src: "/product10.png" },
    category:"Men",
    price:"$225",
    product:"Jacket",
    id:"10",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},{
    name:"Raglan Sweatshirt",
    src: { src: "/product11.png" },
    category:"Men",
    price:"$195",
    product:"Sweater",
    id:"11",
    productDetail:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    productCare:["Hand wash using cold water.",
    "Do not using bleach.",
    "Hang it to dry.",
    " Iron on low temperature."]
},
];