import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Page/NavBar";
import Footer from "@/components/Page/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce Website",
  description: "Generated by Muhammad AbdulRehman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-6 md:px-14`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
